### ISSUE TITLE
Missing LICENSE Files in Rust Crates

### ISSUE THREAD

**Issue by damaestro** [OpenByteDev/dlopen2#12]
MIT license require that redistributed sources contain a copy of the license text. These licenses are not being shipped in the crates:

https://crates.io/crates/dlopen2
https://crates.io/crates/dlopen2_derive

**Comment by decathorpe** [comment]
Note that the commit that closed this issue is not correct. The `package.license-file` setting is only supposed to be used for non-standard licenses that cannot be expressed with SPDX identifiers: https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields

For example, crates.io will show "Non-Standard" license if the `license-file` key is present in crate metadata.

There is no way to make cargo include files from outside the crate directory that is purely in Cargo.toml metadata. You will need to include a copy of the file in the crate directories, or include a symbolic link to the license file(s) if the OS you are running `cargo publish` on supports symbolic links.
